myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: "50"  

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['joint_L1', 'joint_L2']
    right_wheel: ['joint_R1','joint_R2']
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]



# diff_drive_controller:
# type: "diff_drive_controller/DiffDriveController"
# left_wheels: ['joint_L1', 'joint_L2']
# right_wheels: ['joint_R1', 'joint_R2']
# publish_rate: 50
# pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
# twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
# cmd_vel_timeout: 0.25

  # Wheel separation and radius multipliers
# wheel_separation_multiplier: 1.5 # default: 1.0
# wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
# linear:
#   x:
#     has_velocity_limits    : true
#     max_velocity           : 2.0   # m/s
#     has_acceleration_limits: true
#     max_acceleration       : 20.0   # m/s^2
# angular:
#   z:
#     has_velocity_limits    : true
#     max_velocity           : 4.0   # rad/s
#    has_acceleration_limits: true
#     max_acceleration       : 25.0   # rad/s^2
